language: node_js
node_js:
- '12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=ecoledirecte)
  - secure: VSx690saXl5q9gwpyLpS4O/G5jccyXu47OzyfcILcig7XdfvVgdylkXS2bf08Uc+AxOleFV+xYnP5tcJldVucB5nv865poHM/5Jetc5ExAH7WM3whA9Os/fSjsR9vKLhF02MQNIIeofdTfd4dpC5H+TMPgw+DMqFzrraaCLJDOC+Az7/zVEFWa0f1rdfqRMKFKdV2M8LhXoMYVxXAXNpqO/KwSwJyjWFnFW5VjcA8SQb+MhJOoj6+aXGwaTd4GJ6bF75ABwUke26OnNE7LK/oWLW1Oy85ls9fau/uZkGNFgJzPonMKT8DutC21M4Y+3J1EkpUc9mJ+/3RItD8zDbLEXLh+rFQV1ZwmGoiHEb5TvMRAdRxeX3j4hvn1u0rsJhdigvR3iyTfOamBg66UvTcDaS9x/qrBVTD2HjVAMYaDzLfunMtULfWo9zvBiqxzsfYuJlNqa/KbE01eH6zGYKUxH9dz4i6OSUXemHFvR17QnvI34aAUouolw28sPHWCvk9pwu+Zhefo+GahEqesNYG/Uotwqr2bz42l0wUS6ZHFPKFw3GKlsrRbtv/KO+FCXoaOEStvt59U6yIz33iDpFJYaZTDx0uh4riV+Li8FGJSjjqORn1ZgzfwWYUq2uB2clBO/aceqvH16U60ZOHzRKjSB8s74Fv1rpbtcu66A6Lh0=
  # MATTERMOST_HOOK_URL
  - secure: Ltj29DGWqhpTcZ+deM8pKFvHa+0gxQuWnxsPtRqj+McaytSPXZFC5M6CfqSX/RFoQKNtXJt+Ygc4pH377uusMeJD6+/mxNFzTuHJTMxZrW5Wqr+hWyaFYzweKXzRCLE7IbtZu+qgfYl07IJqrc2JFqzrdtMsGErMUsCQS6uZbTKsGW0tWoLSoVX6xPp+WVkqWeRhkhtwFnwHReUWyBbwd6wSYvPoa4dofQ4pfFS6Pvl7w11/4+pyqlbQSuH2XuSznDTb/dzcbgOini5qK5bDRzPaXajqjPhNSI9fNSkXeTriXQ7phiMPq6he/2B/1neVUwu61QakIgrid51p9WQ5eK7hR5364JW11dpWdXx5dF8tM+EWd+3gGfl8IBKrcHPZsjYtFY7qbNTVwqP4SirfdIq4bOm7NxHASDucb5b0Wn7lzoytseLd5PhjoNIV3J9oWw5aFu+vr5n8BCyIKx9353C+myl9Sf2RNftrOQMGncwcd6P+Ohof0i/LVmIU9m1u3XnBwe+AgbiPCtrlRR7Ak4BOI0koeM/FVCMd8LBbdJyifSL/xgID4MM4bkTsyyK6/52kWSz/1XYnqw4rxHftCO/YzkytFRJn9de9s7MUyebJnawBrSW1epg7ovMvykhXq9R4ycbAjv5B0rtZLV64wgN+k54fmdNru61QE/ZeGuU=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_c7cea85e517c_key -iv $encrypted_c7cea85e517c_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
